version: '2'
services:
    74.dap.test:
        image: cicnavi/dap:7.4
        container_name: 74.dap.test
#        restart: unless-stopped
        ports:
        - "8074:80" # web
        - "9074:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./7.4/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./7.4/html:/var/www/html" # Public directory, change local path as needed.
            - "./7.4/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.

    73.dap.test:
        image: cicnavi/dap:7.3
        container_name: 73.dap.test
#        restart: unless-stopped
        ports:
        - "8073:80" # web
        - "9073:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./7.3/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./7.3/html:/var/www/html" # Public directory, change local path as needed.
            - "./7.3/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.

    72.dap.test:
        image: cicnavi/dap:7.2
        container_name: 72.dap.test
#        restart: unless-stopped
        ports:
        - "8072:80" # web
        - "9072:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./7.2/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./7.2/html:/var/www/html" # Public directory, change local path as needed.
            - "./7.2/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.

    71.dap.test:
        image: cicnavi/dap:7.1
        container_name: 71.dap.test
#        restart: unless-stopped
        ports:
        - "8071:80" # web
        - "9071:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./7.1/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./7.1/html:/var/www/html" # Public directory, change local path as needed.
            - "./7.1/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.
            
    70.dap.test:
        image: cicnavi/dap:7.0
        container_name: 70.dap.test
#        restart: unless-stopped
        ports:
        - "8070:80" # web
        - "9070:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./7.0/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./7.0/html:/var/www/html" # Public directory, change local path as needed.
            - "./7.0/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.
    
    56.dap.test:
        image: cicnavi/dap:5.6
        container_name: 56.dap.test
#        restart: unless-stopped
        ports:
        - "8056:80" # web
        - "9056:443" # tls
        volumes:
            - ~/.composer:/root/.composer # Use for composer caching
#            - ~/.gitconfig:/root/.gitconfig # Git configuration ( access alias && config )
            - ~/.ssh:/root/.ssh # Ssh keys for easy deployment inside the container
            - "./5.6/src:/var/www/src" # Directory for all apps, change local path as needed.
            - "./5.6/html:/var/www/html" # Public directory, change local path as needed.
            - "./5.6/apache-config:/etc/apache2/config-from-host" # Optional Apache configuration to include.
            - "./shared:/var/www/shared" # Shared directory between containers.
            
    mysql.dap.test:
        image: mysql:5.7
        container_name: mysql.dap.test
#        restart: unless-stopped
        ports:
            - "33306:3306"
        environment:
# We can run MySQL without root password, or we can set it here.
# Comment out one of the next two lines:    
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#            MYSQL_ROOT_PASSWORD: changeMe
        volumes:
            - ~/volumes/mysql:/var/lib/mysql
            - "./shared:/var/www/shared" # Shared directory between containers.